// 用户要求跳过继续采样：用当前作者源多角度渲染生成自包含交付页。
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),audit=JSON.parse(fs.readFileSync(path.join(__dirname,'export-audit.json'),'utf8'));
const views=[['hero','侧前方'],['left','左侧轮廓'],['right','右侧轮廓'],['front','正面'],['back','尾部'],['top','顶部'],['bottom','腹部'],['icon-shark','透明图标']];
const data=views.map(([key,label])=>({label,url:'data:image/png;base64,'+fs.readFileSync(path.join(__dirname,key+'.png')).toString('base64')}));
const glb='data:model/gltf-binary;base64,'+fs.readFileSync(path.join(root,audit.runtime)).toString('base64');
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><title>充气玩具鲨 · D 交付</title>
<style>*{box-sizing:border-box}body{margin:0;background:#102734;color:#e5f4f6;font:16px/1.75 system-ui,sans-serif}main{max-width:960px;margin:auto;padding:24px}h1{font-size:28px;margin:8px 0}p{color:#c1d6de}button,a.download{display:inline-block;background:#255369;color:#fff;border:1px solid #52778b;border-radius:8px;padding:7px 14px;margin:4px;font:inherit;cursor:pointer}button[aria-pressed=true]{background:#398b95;border-color:#9bf5e0}#hero{display:block;width:min(100%,640px);margin:16px auto;border-radius:14px;background:#345262}section{padding:16px;border:1px solid #365365;border-radius:12px;margin:18px 0}b{color:#b5f4e5}.steps{display:flex;gap:10px;flex-wrap:wrap}.steps span{background:#234b5b;padding:5px 10px;border-radius:7px}small{color:#b5cbd3}a{color:#97e8db}table{width:100%;border-collapse:collapse}td{padding:7px;border-bottom:1px solid #365365}@media(max-width:500px){main{padding:12px}h1{font-size:24px}}</style>
<main><h1>充气玩具鲨</h1><p>修长身体、收窄头腹、后掠软鳍与清晰分叉尾；圆钝鼻头、闭合笑脸、鳃纹和充气阀保留。当前版本按反馈调整，不再采用过圆的胖头轮廓。</p><nav id="views" aria-label="模型观察角度"></nav><img id="hero" alt="玩具鲨侧前方"><section><b>已接入的动作流程</b><div class="steps"><span>水下上浮</span><span>游动追逐</span><span>短暂蓄势</span><span>圆鼻顶推</span><span>轻微回弹</span><span>恢复游动</span></div><p>三段骨骼动作保留在当前 GLB 内，正式追逐和巡游补命中使用同一套接触表现。默认 0.09 秒接触、0.38 秒表现窗；命中后复用 B1 浮圈恢复，入场复用现有 B2 水花。原判定范围、冷却和比赛结果不变。</p><small>按用户要求，最终改形后跳过继续动作采样。本页展示新模型多角度和图标，不提供旧圆形版本的动作画面，不把静态预览当作动作或实机验收。</small></section><section><b>文件审计</b><table><tr><td>网格／材质／纹理</td><td>1／1／0</td></tr><tr><td>骨骼／三角面</td><td>7／${audit.triangles}</td></tr><tr><td>当前 GLB</td><td>${audit.bytes.toLocaleString('en-US')} 字节</td></tr><tr><td>与原版骨架绑定矩阵偏差</td><td>${audit.inverse_bind_max_delta}</td></tr><tr><td>资源身份</td><td>原模型路径及主 UUID 保留</td></tr></table><a class="download" href="${glb}" download="SharkModel.glb">下载当前 GLB</a></section><section><b>待验边界</b><p>这些图像由作者源离线渲染，背景和灯光不是游戏水体。正式主视角／画中画中的接触、所有角色与 B1 衔接、微信双机迟到与重开、iOS／Android 材质和性能仍需验证。没有自动启动、重启或截图 Creator；离线通过不等于真机或平台审核通过。</p></section></main>
<script>const VIEWS=${JSON.stringify(data)},hero=document.getElementById('hero'),nav=document.getElementById('views');function selectView(i){hero.src=VIEWS[i].url;hero.alt=VIEWS[i].label;[...nav.children].forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));window.reviewState={view:i,label:VIEWS[i].label};}VIEWS.forEach((v,i)=>{const b=document.createElement('button');b.textContent=v.label;b.onclick=()=>selectView(i);nav.append(b)});selectView(0);</script></html>`;
fs.writeFileSync(path.join(__dirname,'review.html'),html);console.log('已生成最终静态多角度离线交付页',Buffer.byteLength(html));
