// 独立、无外部请求的原版与试稿对比页；不修改运行时资源。
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const dir=__dirname;
const names=[['hero','侧前方'],['left','左侧'],['right','右侧'],['front','正面'],['back','后面'],['top','顶部'],['bottom','底部'],['valve','充气阀近景'],['face','表情与嘴部']];
const image=n=>'data:image/png;base64,'+fs.readFileSync(path.join(dir,n+'.png')).toString('base64');
const images=Object.fromEntries([...names.map(x=>x[0]),'original','original-side'].map(n=>[n,image(n)]));
const glb=fs.readFileSync(path.join(dir,'Shark_Original_Toy_Study.glb'));
const doc=JSON.parse(glb.subarray(20,20+glb.readUInt32LE(12)).toString());
const report=JSON.parse(fs.readFileSync(path.join(dir,'study-audit.json'),'utf8'));
const triangles=doc.meshes.reduce((sum,m)=>sum+m.primitives.reduce((s,p)=>s+doc.accessors[p.indices].count/3,0),0);
if(triangles!==report.triangles||doc.skins[0].joints.length!==7||doc.meshes.length!==1||(doc.images?.length||0)!==0||doc.materials.length!==1)throw Error('GLB 与源审计不一致');
if(!doc.meshes[0].primitives.every(p=>'COLOR_0' in p.attributes&&'JOINTS_0' in p.attributes&&'WEIGHTS_0' in p.attributes))throw Error('缺失顶点色或蒙皮');
const before=fs.readFileSync(path.join(dir,'../archive/SharkModel_pre_D.blend'));
if(crypto.createHash('sha256').update(before).digest('hex')!==report.source_sha256)throw Error('原版源文件变化');
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>原鲨鱼 · 充气玩具试稿</title><style>
*{box-sizing:border-box}body{margin:0;background:#11252e;color:#e5f2f4;font:16px/1.65 system-ui,sans-serif}main{max-width:1260px;margin:auto;padding:28px 20px 50px}h1{font-size:clamp(25px,4vw,39px);line-height:1.2;margin:8px 0 14px}p{color:#b8cdd3;margin:8px 0 20px}.tag{color:#70d6d2;font-size:13px}.compare{display:grid;grid-template-columns:1fr 1fr;gap:14px}.card{border:1px solid #3a5560;border-radius:14px;overflow:hidden;background:#263e49}.caption{padding:12px 16px;font-weight:600}.card img{display:block;width:100%;height:auto}nav{display:flex;gap:8px;flex-wrap:wrap;margin:26px 0 14px}button,a{font:inherit}button{border:1px solid #53717b;background:#1c3843;color:#dfeff1;border-radius:20px;padding:7px 15px;cursor:pointer}button.on{background:#74d5cf;color:#102e37;border-color:#74d5cf}.view{max-width:1000px;margin:auto}.view img{display:block;width:100%;border-radius:14px}a{color:#80ded6}.notes{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:24px 0}.note{border-top:1px solid #43616c;padding-top:12px}.note p{font-size:14px;margin:6px 0}.footer{font-size:13px;color:#95b1bb;margin-top:24px}@media(max-width:680px){.compare,.notes{grid-template-columns:1fr}main{padding:20px 12px}h1{font-size:27px}nav{gap:6px}button{padding:6px 11px;font-size:14px}}
</style><main><div class="tag">造型试稿 · 2026-09-27</div><h1>原来的鲨鱼，做成充气玩具</h1><p>直接修改 8+ 调整前的原网格，保留头身比例、长吻、背鳍和分叉尾。两张对照使用相同镜头与光照。</p><div class="compare"><div class="card"><div class="caption">8+ 调整前的原鲨鱼</div><img src="${images.original}" alt="原鲨鱼"></div><div class="card"><div class="caption">本次充气玩具试稿</div><img src="${images.hero}" alt="充气鲨鱼试稿"></div></div><div class="notes"><div class="note"><b>原轮廓保留</b><p>沿用原网格；仅微调鳍尖与眉峰，缩短并柔化原牙齿。</p></div><div class="note"><b>玩具细节</b><p>后侧增设橙色充气塞、连体拉片，以及两侧细热压接缝。</p></div><div class="note"><b>软塑料配色</b><p>蓝青背部、浅色腹部，去掉原贴图的写实脏色，保留调皮眉眼。</p></div></div><nav>${names.map(([id,label],i)=>`<button data-id="${id}" class="${i?'':'on'}">${label}</button>`).join('')}</nav><div class="view"><img id="view" src="${images.hero}" alt="侧前方"></div><p class="footer">独立作者模型预览，尚未替换游戏资源。此 GLB 用于静态造型审阅，保留原骨架与蒙皮；未导出动作，也未进行引擎或真机验证。${triangles.toLocaleString()} 三角面 · 1 网格 · 1 材质 · 无贴图。</p><a download="Shark_Original_Toy_Study.glb" href="data:model/gltf-binary;base64,${glb.toString('base64')}">下载试稿 GLB</a></main><script>const images=${JSON.stringify(images)};const view=document.getElementById('view');document.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.on')?.classList.remove('on');button.classList.add('on');view.src=images[button.dataset.id];view.alt=button.textContent}));</script></html>`;
fs.writeFileSync(path.join(dir,'review.html'),html);
fs.writeFileSync(path.join(dir,'delivery-audit.json'),JSON.stringify({triangles,meshes:doc.meshes.length,materials:doc.materials.length,textures:doc.images?.length||0,bones:doc.skins[0].joints.length,animations:doc.animations?.length||0,glb_bytes:glb.length,original_source_unchanged:true,embedded_views:names.length+2,external_requests:0,review_bytes:Buffer.byteLength(html)},null,2));
console.log('试稿 GLB 与原源校验通过；自包含对比页已生成。');
