export type DivePrepBoneName =
    | 'Root'
    | 'Hip'
    | 'Waist'
    | 'Spine01'
    | 'Spine02'
    | 'NeckTwist01'
    | 'Head'
    | 'L_Clavicle'
    | 'L_Upperarm'
    | 'L_Forearm'
    | 'L_Hand'
    | 'R_Clavicle'
    | 'R_Upperarm'
    | 'R_Forearm'
    | 'R_Hand'
    | 'L_Thigh'
    | 'L_Calf'
    | 'L_Foot'
    | 'L_ToeBase'
    | 'R_Thigh'
    | 'R_Calf'
    | 'R_Foot'
    | 'R_ToeBase'
;

export type DivePrepPoseSample = {
    source: string;
    frameStart: number;
    frameEnd: number;
    sampleFrame: number;
    root: readonly [number, number, number];
    head: readonly [number, number, number];
    leftHand: readonly [number, number, number];
    rightHand: readonly [number, number, number];
    leftFoot: readonly [number, number, number];
    rightFoot: readonly [number, number, number];
    rotations: Readonly<Partial<Record<DivePrepBoneName, readonly [number, number, number, number]>>>;
};

// Generated by tools/extract-dive-prep-pose.py from the last retargeted frame of Sumo High Pull.fbx.
export const DIVE_PREP_POSE_SAMPLE: DivePrepPoseSample = {
    "source": "Sumo High Pull.fbx",
    "frameStart": 1,
    "frameEnd": 126,
    "sampleFrame": 126,
    "root": [
        0.0072,
        -0.0164,
        0.0
    ],
    "head": [
        -0.0002,
        -0.2771,
        0.1147
    ],
    "leftHand": [
        0.0498,
        -0.2017,
        -0.2253
    ],
    "rightHand": [
        -0.0571,
        -0.2126,
        -0.2305
    ],
    "leftFoot": [
        0.1168,
        -0.1201,
        -0.3246
    ],
    "rightFoot": [
        -0.0974,
        -0.1447,
        -0.3338
    ],
    "rotations": {
        "Root": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "Hip": [
            0.0,
            0.0,
            -0.0,
            1.0
        ],
        "Waist": [
            -0.548884,
            -0.0,
            -0.00429,
            0.835887
        ],
        "Spine01": [
            -0.067736,
            0.0,
            -0.002122,
            0.997701
        ],
        "Spine02": [
            -0.080701,
            0.0,
            -0.00526,
            0.996724
        ],
        "NeckTwist01": [
            0.146124,
            -0.0,
            0.033249,
            0.988707
        ],
        "Head": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Clavicle": [
            0.041698,
            0.0,
            -0.208653,
            0.9771
        ],
        "L_Upperarm": [
            0.589935,
            0.0,
            -0.388806,
            0.707677
        ],
        "L_Forearm": [
            -0.142973,
            -0.0,
            -0.170894,
            0.974861
        ],
        "L_Hand": [
            0.0,
            -0.0,
            -0.0,
            1.0
        ],
        "R_Clavicle": [
            0.072885,
            -0.0,
            0.276327,
            0.958296
        ],
        "R_Upperarm": [
            0.625012,
            -0.0,
            0.372744,
            0.685873
        ],
        "R_Forearm": [
            -0.129244,
            -0.0,
            0.167323,
            0.977394
        ],
        "R_Hand": [
            -0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Thigh": [
            0.603204,
            0.0,
            0.220495,
            0.766503
        ],
        "L_Calf": [
            -0.677522,
            -0.0,
            -0.297065,
            0.672842
        ],
        "L_Foot": [
            0.0,
            0.0,
            -0.0,
            1.0
        ],
        "L_ToeBase": [
            -0.0,
            -0.0,
            -0.0,
            1.0
        ],
        "R_Thigh": [
            0.612199,
            0.0,
            -0.227436,
            0.757288
        ],
        "R_Calf": [
            -0.647079,
            -1e-06,
            0.367519,
            0.667995
        ],
        "R_Foot": [
            -0.0,
            0.0,
            -0.0,
            1.0
        ],
        "R_ToeBase": [
            0.0,
            -0.0,
            -0.0,
            1.0
        ]
    }
} as const;
