export type DivePrepBoneName =
    | 'Root'
    | 'Hip'
    | 'Waist'
    | 'Spine01'
    | 'Spine02'
    | 'NeckTwist01'
    | 'Head'
    | 'L_Clavicle'
    | 'L_Upperarm'
    | 'L_Forearm'
    | 'L_Hand'
    | 'R_Clavicle'
    | 'R_Upperarm'
    | 'R_Forearm'
    | 'R_Hand'
    | 'L_Thigh'
    | 'L_Calf'
    | 'L_Foot'
    | 'L_ToeBase'
    | 'R_Thigh'
    | 'R_Calf'
    | 'R_Foot'
    | 'R_ToeBase'
;

export type DivePrepPoseSample = {
    source: string;
    frameStart: number;
    frameEnd: number;
    sampleFrame: number;
    root: readonly [number, number, number];
    head: readonly [number, number, number];
    leftHand: readonly [number, number, number];
    rightHand: readonly [number, number, number];
    leftFoot: readonly [number, number, number];
    rightFoot: readonly [number, number, number];
    rotations: Readonly<Partial<Record<DivePrepBoneName, readonly [number, number, number, number]>>>;
};

// Generated by tools/export-dive-prep-pose-from-blend.py from tools/UserSwimmer0621_2DivePrepPose.blend.
export const DIVE_PREP_POSE_SAMPLE: DivePrepPoseSample = {
    "source": "UserSwimmer0621_2DivePrepPose.blend",
    "frameStart": 101,
    "frameEnd": 101,
    "sampleFrame": 101,
    "root": [
        0.0072,
        -0.0164,
        0.0
    ],
    "head": [
        -0.006,
        -0.267,
        -0.1237
    ],
    "leftHand": [
        0.0993,
        -0.2786,
        -0.4159
    ],
    "rightHand": [
        -0.1206,
        -0.256,
        -0.4248
    ],
    "leftFoot": [
        0.1159,
        -0.0983,
        -0.4632
    ],
    "rightFoot": [
        -0.11,
        0.1138,
        -0.3415
    ],
    "rotations": {
        "Root": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "Hip": [
            0.243984,
            -0.009592,
            -0.231211,
            0.941765
        ],
        "Waist": [
            -0.548563,
            -0.0,
            -0.004348,
            0.836098
        ],
        "Spine01": [
            -0.067752,
            0.0,
            -0.002493,
            0.997699
        ],
        "Spine02": [
            -0.227211,
            0.003828,
            -0.040606,
            0.972991
        ],
        "NeckTwist01": [
            0.146232,
            -0.0,
            0.035076,
            0.988623
        ],
        "Head": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Clavicle": [
            -0.072467,
            -0.01292,
            0.058615,
            0.995562
        ],
        "L_Upperarm": [
            0.89046,
            -0.084697,
            -0.34598,
            0.2832
        ],
        "L_Forearm": [
            -0.14306,
            0.0,
            -0.17089,
            0.974849
        ],
        "L_Hand": [
            0.0,
            -0.0,
            -0.0,
            1.0
        ],
        "R_Clavicle": [
            -0.067017,
            -0.02043,
            -0.111592,
            0.991282
        ],
        "R_Upperarm": [
            0.901852,
            0.102461,
            0.323403,
            0.267537
        ],
        "R_Forearm": [
            -0.14306,
            -0.0,
            0.17089,
            0.974849
        ],
        "R_Hand": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Thigh": [
            0.603378,
            0.0,
            0.220505,
            0.766363
        ],
        "L_Calf": [
            -0.266415,
            0.023602,
            -0.325514,
            0.906922
        ],
        "L_Foot": [
            0.0,
            0.0,
            -0.0,
            1.0
        ],
        "L_ToeBase": [
            -0.0,
            -0.0,
            -0.0,
            1.0
        ],
        "R_Thigh": [
            0.603378,
            -0.0,
            -0.220505,
            0.766363
        ],
        "R_Calf": [
            -0.677633,
            0.0,
            0.297204,
            0.672669
        ],
        "R_Foot": [
            0.0,
            -0.0,
            0.0,
            1.0
        ],
        "R_ToeBase": [
            -0.0,
            0.0,
            0.0,
            1.0
        ]
    }
} as const;
