export type DivePrepBoneName =
    | 'Root'
    | 'Hip'
    | 'Waist'
    | 'Spine01'
    | 'Spine02'
    | 'NeckTwist01'
    | 'Head'
    | 'L_Clavicle'
    | 'L_Upperarm'
    | 'L_Forearm'
    | 'L_Hand'
    | 'R_Clavicle'
    | 'R_Upperarm'
    | 'R_Forearm'
    | 'R_Hand'
    | 'L_Thigh'
    | 'L_Calf'
    | 'L_Foot'
    | 'L_ToeBase'
    | 'R_Thigh'
    | 'R_Calf'
    | 'R_Foot'
    | 'R_ToeBase'
;

export type DivePrepPoseSample = {
    source: string;
    frameStart: number;
    frameEnd: number;
    sampleFrame: number;
    root: readonly [number, number, number];
    head: readonly [number, number, number];
    leftHand: readonly [number, number, number];
    rightHand: readonly [number, number, number];
    leftFoot: readonly [number, number, number];
    rightFoot: readonly [number, number, number];
    rotations: Readonly<Partial<Record<DivePrepBoneName, readonly [number, number, number, number]>>>;
};

// Generated by tools/export-dive-prep-pose-from-blend.py from tools/UserSwimmer0621_2DivePrepPose.blend.
export const DIVE_PREP_POSE_SAMPLE: DivePrepPoseSample = {
    "source": "UserSwimmer0621_2DivePrepPose.blend",
    "frameStart": 101,
    "frameEnd": 101,
    "sampleFrame": 101,
    "root": [
        0.0072,
        -0.0164,
        0.0
    ],
    "head": [
        -0.0046,
        -0.2927,
        -0.0617
    ],
    "leftHand": [
        0.1011,
        -0.281,
        -0.3662
    ],
    "rightHand": [
        -0.1314,
        -0.2724,
        -0.3683
    ],
    "leftFoot": [
        0.1527,
        -0.1506,
        -0.4378
    ],
    "rightFoot": [
        -0.1488,
        -0.1502,
        -0.474
    ],
    "rotations": {
        "Root": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "Hip": [
            0.192885,
            -0.015037,
            -0.201777,
            0.960133
        ],
        "Waist": [
            -0.548563,
            -0.0,
            -0.004348,
            0.836098
        ],
        "Spine01": [
            -0.067752,
            0.0,
            -0.002493,
            0.997699
        ],
        "Spine02": [
            -0.117398,
            -0.00237,
            0.003619,
            0.993075
        ],
        "NeckTwist01": [
            0.146232,
            -0.0,
            0.035076,
            0.988623
        ],
        "Head": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Clavicle": [
            -0.043041,
            -0.002897,
            0.119842,
            0.991855
        ],
        "L_Upperarm": [
            0.849361,
            0.124461,
            0.096994,
            0.503672
        ],
        "L_Forearm": [
            -0.112252,
            0.121335,
            0.005377,
            0.986229
        ],
        "L_Hand": [
            -0.113928,
            0.005497,
            0.034488,
            0.992875
        ],
        "R_Clavicle": [
            -0.043041,
            0.002897,
            -0.119842,
            0.991855
        ],
        "R_Upperarm": [
            0.849362,
            -0.124462,
            -0.096994,
            0.503672
        ],
        "R_Forearm": [
            -0.112252,
            -0.121335,
            -0.005377,
            0.986229
        ],
        "R_Hand": [
            -0.113928,
            -0.005497,
            -0.034488,
            0.992875
        ],
        "L_Thigh": [
            0.603378,
            0.0,
            0.220505,
            0.766363
        ],
        "L_Calf": [
            -0.300113,
            0.027183,
            -0.242571,
            0.922146
        ],
        "L_Foot": [
            -0.062089,
            -0.00598,
            0.008563,
            0.998016
        ],
        "L_ToeBase": [
            -0.0,
            -0.0,
            -0.0,
            1.0
        ],
        "R_Thigh": [
            0.603378,
            -0.0,
            -0.220505,
            0.766363
        ],
        "R_Calf": [
            -0.300113,
            -0.027183,
            0.242571,
            0.922146
        ],
        "R_Foot": [
            -0.062089,
            0.00598,
            -0.008563,
            0.998016
        ],
        "R_ToeBase": [
            -0.0,
            0.0,
            0.0,
            1.0
        ]
    }
} as const;
