export type FlipTurnBoneName =
    | 'Root'
    | 'Hip'
    | 'Pelvis'
    | 'Waist'
    | 'Spine01'
    | 'Spine02'
    | 'NeckTwist01'
    | 'Head'
    | 'L_Clavicle'
    | 'L_Upperarm'
    | 'L_Forearm'
    | 'L_Hand'
    | 'R_Clavicle'
    | 'R_Upperarm'
    | 'R_Forearm'
    | 'R_Hand'
    | 'L_Thigh'
    | 'L_Calf'
    | 'L_Foot'
    | 'L_ToeBase'
    | 'R_Thigh'
    | 'R_Calf'
    | 'R_Foot'
    | 'R_ToeBase'
;

export type FlipTurnPoseSample = {
    source: string;
    rootOffset: readonly [number, number, number];
    blenderArmatureLocation: readonly [number, number, number];
    head: readonly [number, number, number];
    leftHand: readonly [number, number, number];
    rightHand: readonly [number, number, number];
    leftFoot: readonly [number, number, number];
    rightFoot: readonly [number, number, number];
    rotations: Readonly<Record<FlipTurnBoneName, readonly [number, number, number, number]>>;
};

// Generated by tools/export-flip-turn-poses-from-blend.py.
// Rotations are offsets relative to the imported UserSwimmer0621_2 base pose.
export const FLIP_TURN_KEYFRAME_1: FlipTurnPoseSample = {
    "source": "UserSwimmer0621_2FlipTurnPose01.blend",
    "rootOffset": [
        0.0,
        0.0,
        -0.0
    ],
    "blenderArmatureLocation": [
        0.0,
        0.0,
        0.0
    ],
    "head": [
        0.01258,
        -0.293758,
        0.012915
    ],
    "leftHand": [
        0.137526,
        -0.047623,
        -0.188783
    ],
    "rightHand": [
        -0.175612,
        -0.028935,
        -0.172499
    ],
    "leftFoot": [
        0.110317,
        0.042375,
        -0.524349
    ],
    "rightFoot": [
        -0.113339,
        0.042338,
        -0.52555
    ],
    "rotations": {
        "Root": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "Hip": [
            0.44424063,
            0.0164735,
            -0.48132423,
            0.75545096
        ],
        "Pelvis": [
            0.00032249,
            0.00537261,
            -0.00199883,
            0.99998361
        ],
        "Waist": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "Spine01": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "Spine02": [
            -0.22720574,
            0.0528122,
            -0.00227633,
            0.9724111
        ],
        "NeckTwist01": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "Head": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Clavicle": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Upperarm": [
            0.44715399,
            -0.01625781,
            -0.26875186,
            0.85297215
        ],
        "L_Forearm": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Hand": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "R_Clavicle": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "R_Upperarm": [
            0.40366113,
            0.07635704,
            0.15838641,
            0.89785361
        ],
        "R_Forearm": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "R_Hand": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Thigh": [
            0.65393227,
            0.02030803,
            0.09934843,
            0.74972665
        ],
        "L_Calf": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Foot": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_ToeBase": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "R_Thigh": [
            0.65569007,
            0.01361003,
            -0.0539929,
            0.75297427
        ],
        "R_Calf": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "R_Foot": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "R_ToeBase": [
            0.0,
            0.0,
            0.0,
            1.0
        ]
    }
} as const;

export const FLIP_TURN_KEYFRAME_2: FlipTurnPoseSample = {
    "source": "UserSwimmer0621_2FlipTurnPose02.blend",
    "rootOffset": [
        0.0,
        -0.310092,
        -0.0
    ],
    "blenderArmatureLocation": [
        0.0,
        0.0,
        -0.310092
    ],
    "head": [
        0.014203,
        -0.035158,
        0.291857
    ],
    "leftHand": [
        0.162038,
        -0.08609,
        -0.036367
    ],
    "rightHand": [
        -0.204903,
        -0.067794,
        -0.022045
    ],
    "leftFoot": [
        0.044652,
        -0.093115,
        -0.210753
    ],
    "rightFoot": [
        -0.149508,
        -0.134382,
        -0.201859
    ],
    "rotations": {
        "Root": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "Hip": [
            -0.02688224,
            -0.0203556,
            -0.03819026,
            0.99870151
        ],
        "Pelvis": [
            0.19457248,
            -0.00211735,
            -0.01281529,
            0.98080224
        ],
        "Waist": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "Spine01": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "Spine02": [
            -0.22720574,
            0.0528122,
            -0.00227633,
            0.9724111
        ],
        "NeckTwist01": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "Head": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Clavicle": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Upperarm": [
            0.27726653,
            -0.06194053,
            -0.15180549,
            0.94670057
        ],
        "L_Forearm": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Hand": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "R_Clavicle": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "R_Upperarm": [
            0.27754724,
            0.06899267,
            0.07717682,
            0.9551186
        ],
        "R_Forearm": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "R_Hand": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "L_Thigh": [
            0.65393227,
            0.02030803,
            0.09934843,
            0.74972665
        ],
        "L_Calf": [
            -0.89151794,
            -0.02816047,
            -0.17864969,
            0.41531557
        ],
        "L_Foot": [
            0.2016602,
            0.01549602,
            -0.00668701,
            0.97931015
        ],
        "L_ToeBase": [
            0.0,
            0.0,
            0.0,
            1.0
        ],
        "R_Thigh": [
            0.70802903,
            0.01676212,
            -0.03344246,
            0.70519191
        ],
        "R_Calf": [
            -0.87910318,
            -0.09719338,
            0.0420352,
            0.46471927
        ],
        "R_Foot": [
            0.05787473,
            0.00907891,
            -0.01008383,
            0.99823171
        ],
        "R_ToeBase": [
            0.0,
            0.0,
            0.0,
            1.0
        ]
    }
} as const;
