import json
import os

import bpy


PROJECT_ROOT = r"F:\myworkspace\cocosProjects\SpeedSwimming"
SOURCE_GLB = os.path.join(PROJECT_ROOT, "assets", "resources", "models", "UserSwimmer0621_2SumoHighPull.glb")
OUTPUT_TS = os.path.join(PROJECT_ROOT, "assets", "scripts", "character", "DivePrepPoseCurve.ts")


def clear_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete()


def vector_tuple(vec):
    return [round(float(vec.x), 4), round(float(vec.y), 4), round(float(vec.z), 4)]


def quat_tuple(quat):
    return [
        round(float(quat.x), 6),
        round(float(quat.y), 6),
        round(float(quat.z), 6),
        round(float(quat.w), 6),
    ]


def main():
    clear_scene()
    bpy.ops.import_scene.gltf(filepath=SOURCE_GLB)
    armature = next(obj for obj in bpy.context.scene.objects if obj.type == "ARMATURE")
    action = armature.animation_data.action if armature.animation_data else None
    if not action:
        raise RuntimeError("source action missing")

    frame_start = int(action.frame_range[0])
    frame_end = int(action.frame_range[1])
    sample_frame = frame_end
    bpy.context.scene.frame_set(sample_frame)

    def pose_bone(name):
        return armature.pose.bones[name]

    def bone_world(name):
        return armature.matrix_world @ pose_bone(name).head

    sampled_bones = [
        "Root",
        "Hip",
        "Waist",
        "Spine01",
        "Spine02",
        "NeckTwist01",
        "Head",
        "L_Clavicle",
        "L_Upperarm",
        "L_Forearm",
        "L_Hand",
        "R_Clavicle",
        "R_Upperarm",
        "R_Forearm",
        "R_Hand",
        "L_Thigh",
        "L_Calf",
        "L_Foot",
        "L_ToeBase",
        "R_Thigh",
        "R_Calf",
        "R_Foot",
        "R_ToeBase",
    ]
    hip = bone_world("Hip")
    root = bone_world("Root")
    sample = {
        "source": "Sumo High Pull.fbx",
        "frameStart": frame_start,
        "frameEnd": frame_end,
        "sampleFrame": sample_frame,
        "root": vector_tuple(root),
        "head": vector_tuple(bone_world("Head") - hip),
        "leftHand": vector_tuple(bone_world("L_Hand") - hip),
        "rightHand": vector_tuple(bone_world("R_Hand") - hip),
        "leftFoot": vector_tuple(bone_world("L_Foot") - hip),
        "rightFoot": vector_tuple(bone_world("R_Foot") - hip),
        "rotations": {},
    }
    for bone_name in sampled_bones:
        if bone_name in armature.pose.bones:
            sample["rotations"][bone_name] = quat_tuple(pose_bone(bone_name).rotation_quaternion)

    content = [
        "export type DivePrepBoneName =",
        *[f"    | '{bone_name}'" for bone_name in sampled_bones],
        ";",
        "",
        "export type DivePrepPoseSample = {",
        "    source: string;",
        "    frameStart: number;",
        "    frameEnd: number;",
        "    sampleFrame: number;",
        "    root: readonly [number, number, number];",
        "    head: readonly [number, number, number];",
        "    leftHand: readonly [number, number, number];",
        "    rightHand: readonly [number, number, number];",
        "    leftFoot: readonly [number, number, number];",
        "    rightFoot: readonly [number, number, number];",
        "    rotations: Readonly<Partial<Record<DivePrepBoneName, readonly [number, number, number, number]>>>;",
        "};",
        "",
        "// Generated by tools/extract-dive-prep-pose.py from the last retargeted frame of Sumo High Pull.fbx.",
        f"export const DIVE_PREP_POSE_SAMPLE: DivePrepPoseSample = {json.dumps(sample, indent=4)} as const;",
        "",
    ]
    with open(OUTPUT_TS, "w", encoding="utf-8", newline="\n") as file:
        file.write("\n".join(content))

    print(json.dumps({
        "source": SOURCE_GLB,
        "output": OUTPUT_TS,
        "frame_start": frame_start,
        "frame_end": frame_end,
        "sample_frame": sample_frame,
        "bone_count": len(sample["rotations"]),
    }, indent=2))


if __name__ == "__main__":
    main()
