import json
import os

import bpy


PROJECT_ROOT = r"F:\myworkspace\cocosProjects\SpeedSwimming"
SOURCE_GLB = os.path.join(PROJECT_ROOT, "assets", "resources", "models", "UserSwimmer0621_2MixamoSwimming.glb")
OUTPUT_TS = os.path.join(PROJECT_ROOT, "assets", "scripts", "character", "BreaststrokeMotionCurve.ts")


def clear_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete()


def vector_tuple(vec):
    return [round(float(vec.x), 4), round(float(vec.y), 4), round(float(vec.z), 4)]


def quat_tuple(quat):
    return [
        round(float(quat.x), 6),
        round(float(quat.y), 6),
        round(float(quat.z), 6),
        round(float(quat.w), 6),
    ]


def main():
    clear_scene()
    bpy.ops.import_scene.gltf(filepath=SOURCE_GLB)
    armature = next(obj for obj in bpy.context.scene.objects if obj.type == "ARMATURE")
    action = armature.animation_data.action if armature.animation_data else None
    if not action:
        raise RuntimeError("source action missing")

    frame_start = int(action.frame_range[0])
    frame_end = int(action.frame_range[1])
    sample_count = 25

    def pose_bone(name):
        return armature.pose.bones[name]

    def bone_world(name):
        return armature.matrix_world @ pose_bone(name).head

    sampled_bones = [
        "Root",
        "Hip",
        "Waist",
        "Spine01",
        "Spine02",
        "NeckTwist01",
        "Head",
        "L_Clavicle",
        "L_Upperarm",
        "L_Forearm",
        "L_Hand",
        "R_Clavicle",
        "R_Upperarm",
        "R_Forearm",
        "R_Hand",
        "L_Thigh",
        "L_Calf",
        "L_Foot",
        "L_ToeBase",
        "R_Thigh",
        "R_Calf",
        "R_Foot",
        "R_ToeBase",
    ]
    samples = []
    for index in range(sample_count):
        t = index / (sample_count - 1)
        frame = round(frame_start + (frame_end - frame_start) * t)
        bpy.context.scene.frame_set(frame)
        hip = bone_world("Hip")
        root = bone_world("Root")
        head = bone_world("Head") - hip
        left_hand = bone_world("L_Hand") - hip
        left_foot = bone_world("L_Foot") - hip
        rotations = {}
        for bone_name in sampled_bones:
            if bone_name not in armature.pose.bones:
                continue
            rotations[bone_name] = quat_tuple(pose_bone(bone_name).rotation_quaternion)
        samples.append({
            "phase": round(t, 4),
            "root": vector_tuple(root),
            "head": vector_tuple(head),
            "hand": vector_tuple(left_hand),
            "foot": vector_tuple(left_foot),
            "rotations": rotations,
        })

    content = [
        "export type BreaststrokeBoneName =",
        *[f"    | '{bone_name}'" for bone_name in sampled_bones],
        ";",
        "",
        "export type BreaststrokeMotionSample = {",
        "    phase: number;",
        "    root: readonly [number, number, number];",
        "    head: readonly [number, number, number];",
        "    hand: readonly [number, number, number];",
        "    foot: readonly [number, number, number];",
        "    rotations: Readonly<Partial<Record<BreaststrokeBoneName, readonly [number, number, number, number]>>>;",
        "};",
        "",
        "// Generated by tools/extract-breaststroke-motion.py from UserSwimmer0621_2MixamoSwimming.glb.",
        "// Samples preserve source left/right asymmetry from the imported treading-water action.",
        f"export const BREASTSTROKE_MOTION_SAMPLES: readonly BreaststrokeMotionSample[] = {json.dumps(samples, indent=4)} as const;",
        "",
    ]
    with open(OUTPUT_TS, "w", encoding="utf-8", newline="\n") as file:
        file.write("\n".join(content))

    print(json.dumps({
        "source": SOURCE_GLB,
        "output": OUTPUT_TS,
        "sample_count": sample_count,
        "frame_start": frame_start,
        "frame_end": frame_end,
    }, indent=2))


if __name__ == "__main__":
    main()
