/** 仅本地娱乐调试使用；不覆盖正式比赛数值。 */
export const STIMULANT_BRAWL_TUNING = {
    waveCount: 7,
    itemsPerWave: 3,
    energyRestoreRatio: 0.3,
    heartRateBurden: 40,
    heartRateRecoveryHoldSeconds: 4,
    pickupRadius: 1.2,
    pickupBodyHalfLength: 0.8,
    reactionDuration: 6,
    oversteerStartHeartRate: 130,
    oversteerMaxHeartRate: 180,
    maxTurnImpulseScale: 1.65,
    minTurnDragScale: 0.55,
    aiSkipHeartRate: 165,
    calmSlushHeartRateDrop: 60,
    calmSlushDuration: 3,
    calmSlushPropulsionScale: 0.9,
    calmSlushAiPreferHeartRate: 145,
    calmSlushAiStronglyPreferHeartRate: 165,
};

export const LITTER_BRAWL_TUNING = {
    poolSize: 18,
    waveDistances: [18, 48, 82, 118, 154] as readonly number[],
    waveCount: 6,
    burstGroupIntervalSeconds: 0.34,
    landingLeadDistance: 7,
    fallingSeconds: 1.35,
    contactAlongRadius: 1.25,
    contactLateralRadius: 0.75,
    maxEnvironmentDrag: 0.78,
    swimmerContactAlongRadius: 0.68,
    swimmerContactLateralRadius: 0.4,
    rigidItemAlongRadius: 0.42,
    rigidItemLateralRadius: 0.18,
    softPushContactAlongRadius: 0.48,
    softPushContactLateralRadius: 0.28,
    rigidSpeedRetain: 0.72,
    rigidBackwardImpulse: 0.22,
    rigidLateralImpulse: 0.52,
    rigidDebrisBounceSpeed: 2.45,
    softDebrisPushSpeed: 0.95,
    softDebrisPushDamping: 1.65,
    aiLookAhead: 8,
    safeHalfWidth: 1.45,
    spawnSafetyRetrySeconds: 0.25,
    maxSpawnDelaySeconds: 3,
    spawnSwimmerClearAlongRadius: 2.6,
    spawnMineAlongMargin: 1.25,
    spawnMineLateralMargin: 0.55,
    spawnWhirlpoolAlongMargin: 1.1,
    spawnWhirlpoolLateralMargin: 0.35,
    waterEdgeMargin: 0.9,
    driftAlongRadius: 0.42,
    driftLateralRadius: 0.34,
    driftSpeed: 0.46,
    driftEntryBlendSeconds: 0.8,
    floatingLifetime: 16,
    retireSeconds: 5.5,
};

export const ENTERTAINMENT_DEBUG_TUNING = {
    supplyPoolSize: 6,
    supplyLifetime: 14,
    supplyThrowSeconds: 1.1,
    supplyLeadDistance: 6,
    aiLookAhead: 14,
    debrisItemsPerWave: 3,
    debrisPoolSize: 6,
};

export const WHIRLPOOL_BRAWL_TUNING = {
    alongRadius: 5.2,
    lateralRadius: 4.2,
    coreRadiusRatio: 0.32,
    inwardPullAcceleration: 3.6,
    coreCaptureAcceleration: 2.4,
    captureRadiusRatio: 0.62,
    capturePropulsionDrag: 2.0,
    approachForwardPullScale: 0.25,
    outerInwardScale: 0.58,
    swirlAcceleration: 5.2,
    coreSwirlScale: 0.82,
    outerBoostAcceleration: 2.0,
    outerCounterflowAcceleration: 1.2,
    coreBackwardAcceleration: 6.0,
    yawAccelerationScale: 0.22,
    rollAccelerationScale: 0.42,
    maxFlowSpeed: 3.4,
    submergedInfluenceScale: 0.35,
    flowDecaySeconds: 0.5,
};

export const WHIRLPOOL_SUPER_TUNING = {
    alongRadiusScale: 1.35,
    lateralRadiusScale: 1.5,
    coreRadiusScale: 1.5,
    captureRadiusScale: 1.15,
    captureDragScale: 1.35,
    inwardPullScale: 1.3,
    swirlScale: 1.25,
    outerBoostScale: 1.4,
    outerCounterflowScale: 1.3,
    coreBackwardScale: 1.35,
    maxFlowSpeedScale: 1.08,
};

export const GEYSER_TUNING = {
    warningSeconds: 1.5,
    burstSeconds: 0.95,
    burstRiseSeconds: 0.15,
    fallingSeconds: 0.45,
    restSeconds: 1.8,
    coreRadius: 0.65,
    edgeRadius: 1.2,
    visualWarningRadius: 1.35,
    flightSeconds: 1,
    submergedFlightSeconds: 1.2,
    peakHeight: 1.2,
    entrySpeedScale: 0.75,
    exitSpeedScale: 0.6,
    edgeSlowdownScale: 0.9,
    edgeSeconds: 0.25,
    rehitGraceSeconds: 0.8,
    largeRadiusScale: 1.6,
    largePeakHeightScale: 1.5,
    largeFlightExtraSeconds: 0.1,
    largeWarningLeadSeconds: 0.3,
    largeJetHeightScale: 1.5,
    pitchImpulseMaxDegPerSec: 120,
    rollImpulseMaxDegPerSec: 80,
    pitchMaxDegrees: 50,
    rollMaxDegrees: 35,
    rotationDamping: 2.5,
    grazeTiltMaxDegrees: 10,
    bodyHitLiftMinScale: 0.75,
    landingSettleSeconds: 0.35,
};

export const GIANT_WAVE_TUNING = {
    widthFraction: 0.55, lengthFraction: 0.12, height: 0.48,
    previewSeconds: 3, entranceSeconds: 1.2,
    growthSeconds: 3.5, impactSeconds: 1.2, fadeSeconds: 1, gapSeconds: 5,
    travelSpeed: 4.2, boostSpeed: 1.1, oppositionSlowdown: 0.3,
    riseSeconds: 0.35, releaseSeconds: 0.6,
    oppositionRiseSeconds: 0.12, oppositionReleaseSeconds: 0.2, anchorFraction: 0.04,
};

/** 以原有调参为三档基准；档位只改变覆盖、迎浪压力与间隔，不提高顺浪收益。 */
export const GIANT_WAVE_INTENSITY_TUNING = [
    { widthOffset: -0.20, lengthOffset: -0.04, slowdownOffset: -0.15, gapOffset: 2 },
    { widthOffset: -0.10, lengthOffset: -0.02, slowdownOffset: -0.08, gapOffset: 1 },
    { widthOffset: 0, lengthOffset: 0, slowdownOffset: 0, gapOffset: 0 },
    { widthOffset: 0.10, lengthOffset: 0.02, slowdownOffset: 0.08, gapOffset: -1 },
    { widthOffset: 0.20, lengthOffset: 0.04, slowdownOffset: 0.15, gapOffset: -2 },
];
