/** 仅本地娱乐调试使用；不覆盖正式比赛数值。 */
export const STIMULANT_BRAWL_TUNING = {
    waveCount: 7,
    itemsPerWave: 3,
    energyRestoreRatio: 0.3,
    heartRateBurden: 40,
    heartRateRecoveryHoldSeconds: 4,
    pickupRadius: 1.2,
    pickupBodyHalfLength: 0.8,
    reactionDuration: 6,
    oversteerStartHeartRate: 130,
    oversteerMaxHeartRate: 180,
    maxTurnImpulseScale: 1.65,
    minTurnDragScale: 0.55,
    aiSkipHeartRate: 165,
    calmSlushHeartRateDrop: 60,
    calmSlushDuration: 3,
    calmSlushPropulsionScale: 0.9,
    calmSlushAiPreferHeartRate: 145,
    calmSlushAiStronglyPreferHeartRate: 165,
};

export const LITTER_BRAWL_TUNING = {
    poolSize: 18,
    waveDistances: [18, 48, 82, 118, 154] as readonly number[],
    waveCount: 6,
    burstGroupIntervalSeconds: 0.34,
    landingLeadDistance: 7,
    fallingSeconds: 1.35,
    contactAlongRadius: 1.25,
    contactLateralRadius: 0.75,
    maxEnvironmentDrag: 0.78,
    swimmerContactAlongRadius: 0.68,
    swimmerContactLateralRadius: 0.4,
    rigidItemAlongRadius: 0.42,
    rigidItemLateralRadius: 0.18,
    softPushContactAlongRadius: 0.48,
    softPushContactLateralRadius: 0.28,
    rigidSpeedRetain: 0.72,
    rigidBackwardImpulse: 0.22,
    rigidLateralImpulse: 0.52,
    rigidDebrisBounceSpeed: 2.45,
    softDebrisPushSpeed: 0.95,
    softDebrisPushDamping: 1.65,
    aiLookAhead: 8,
    safeHalfWidth: 1.45,
    spawnSafetyRetrySeconds: 0.25,
    maxSpawnDelaySeconds: 3,
    spawnSwimmerClearAlongRadius: 2.6,
    spawnMineAlongMargin: 1.25,
    spawnMineLateralMargin: 0.55,
    spawnWhirlpoolAlongMargin: 1.1,
    spawnWhirlpoolLateralMargin: 0.35,
    waterEdgeMargin: 0.9,
    driftAlongRadius: 0.42,
    driftLateralRadius: 0.34,
    driftSpeed: 0.46,
    driftEntryBlendSeconds: 0.8,
    floatingLifetime: 16,
    retireSeconds: 5.5,
};

export const ENTERTAINMENT_DEBUG_TUNING = {
    supplyPoolSize: 6,
    supplyLifetime: 14,
    supplyThrowSeconds: 1.1,
    supplyLeadDistance: 6,
    aiLookAhead: 14,
    debrisItemsPerWave: 3,
    debrisPoolSize: 6,
};
